services:
  - type: worker
    name: fsl-token-price-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        value: your_actual_token_here
      - key: UPDATE_FREQUENCY
        value: "3600000"  # 1時間ごと
      - key: UPDATE_STATUS
        value: "on"
      - key: BOARDCAST
        value: "on"
      - key: TARGET_CHANNEL_IDS
        value: "1367887693446643804,1367887745086787594,1367888140534153266"
      - key: MESSAGE_TYPE
        value: "embed"
      - key: CHAIN
        value: "bsc"
      - key: PAIR_HASH
        value: "0x..."  # 必要に応じて
