services:
  - type: web
    name: fsl-token-price-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        value: your_actual_token
      - key: TARGET_CHANNEL_IDS
        value: "1367887693446643804,1367887745086787594,1367888140534153266"
      - key: UPDATE_STATUS
        value: "on"
      - key: UPDATE_FREQUENCY
        value: "3600000"
      - key: BOARDCAST
        value: "on"
      - key: MESSAGE_TYPE
        value: "embed"
